---
title: Algoritma SOM
author: "Zia Zammaira-Institut Teknologi Statistika dan Bisnis Muhammadiyah"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: flatly
    higlight: zenburn
    toc: true
    toc_float:
      collapsed: true
    df_print: paged
bibliography: references.bib
---

```{=html}
<style>
body{
text-align: justify}
</style>
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Algoritma SOM
Setiap titik data dalam kumpulan data mengenali diri mereka sendiri dengan bersaing untuk representasi. Langkah pemetaan SOM dimulai dari inisialisasi vektor bobot. Dari sana vektor sampel dipilih secara acak dan peta vektor bobot dicari untuk menemukan bobot mana yang paling mewakili sampel tersebut. Setiap vektor bobot memiliki bobot lingkungan yang dekat dengannya. Bobot yang dipilih dihargai dengan mampu menjadi lebih seperti vektor sampel yang dipilih secara acak. Tetangga dengan berat itu juga dihargai dengan bisa menjadi lebih seperti vektor sampel yang dipilih. Ini memungkinkan peta tumbuh dan membentuk berbagai bentuk. Umumnya, mereka membentuk bentuk persegi/persegi panjang/heksagonal/L dalam ruang fitur 2D.

SOM menghitung jarak setiap vektor input dengan setiap bobot node. Jarak yang biasa digunakan adalah jarak Euclidean.

#Analisis SOM
Pada artikel ini, kami ingin menggunakan kumpulan data analitik web di San Francisco. Kami ingin mempelajari bagaimana menggunakan SOM untuk mengidentifikasi karakteristik setiap cluster di banyak web di San Francisco dengan beberapa fitur.

#Library yang digunakan
 












# Eksperimen Algoritma SOM

# Referensi


